name: ai_project_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python=3.11
  - pytorch
  - scikit-learn
  - scipy
  - torchaudio
  - torchmetrics
  - torchvision
  - kaggle
  - torchinfo
  - python-dotenv
  - wandb
